app/urls.py
from django.urls import path
from app.views import CategoryView

urlpatterns = [
    path('', CategoryView.as_view(), name='category_view'),
    path('get-subcategory', CategoryView.get_subcategory, name='get_subcategory'),
]

django_task/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models


class Category(models.Model):
    categories = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self):
        return self.categories
    
    class Meta:
        db_table = 'category'


class SubCategory(models.Model):
    subcategory = models.CharField(max_length=30, null=True, blank=True)
    category    = models.ForeignKey(Category, related_name='category', on_delete=models.CASCADE, null=True, blank=True)
        
    class Meta:
        db_table = 'subcategory'

app/forms.py
from django import forms
from app.models import Category, SubCategory


class CategoryForm(forms.ModelForm):
    
    class Meta:
        model = SubCategory
        fields = "__all__"
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
        }

app/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import JsonResponse
from django.contrib import messages

from app.forms import CategoryForm
from app.models import SubCategory


class CategoryView(View):
    """ 
        This View renders the template, 
        get subcategories based on selected category and submits the form 
    """
    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        """ Returns the template with default values """
        form = CategoryForm()
        records = SubCategory.objects.all().order_by('-id')
        context = {
            "form": form,
            "records": records
        }
        return render(request, self.template_name, context)
    
    def get_subcategory(request):
        """ Returns SubCategory Based on selected Category """
        category_id = request.GET.get('category_id')
        try:
            subcategory_objs = SubCategory.objects.filter(category=category_id).values()
            data = {
                'success': True,
                'records': list(subcategory_objs),
            }
        except SubCategory.DoesNotExist:
            data = {
                'success': False,
                'message': "No Data Found!"
            }
        return JsonResponse(data)
    
    def post(self, request, *args, **kwargs):
        """ Submits the form and redirect to the same page """
        print(request.POST)
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            # messages.success(request, "Form Submitted Successfully.")
            # return redirect('/')
            records = SubCategory.objects.all().order_by('-id')
            data = {
                "success": True,
                "message": "Form Submitted Successfully.",
                "records": list(records.values())

            }
            return JsonResponse(data)
        else:
            data = {
                "success": False,
                "errors": form
            }
            return JsonResponse(data)
        # return render(request, self.template_name, {'form': form})


# from flask import Flask
# app = Flask(__name__)

# @app.route('/flask')
# def hello_world():
#     return 'Hello, World!'

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Form</title>
        {% load static %}
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'bootstrap-4.0.0/css/bootstrap.min.css' %}" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <!-- As a heading -->
            <nav class="navbar navbar-light bg-light">
                <span class="navbar-brand mb-0 h1">Category Form</span>
            </nav>
            {% if messages %}
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <span>{{ message }}</span>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            {% endif %}
            <div class="row justify-content-md-center" style="margin-top: 50px;">
                <div class="col-md-8">
                    <form action="" method="POST" id="id_form">{% csrf_token %}
                        <div class="form-group">
                            <label for="{{ form.category.id_for_label }}">Category</label>
                            {{ form.category }}
                        </div>
                        <div class="form-group">
                            <label for="id_subcategory">Sub Category</label>
                            <select class="form-control" id="id_subcategory" name="subcategory">
                                <option value="" selected disabled>Select SubCategory</option>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary" id="btn_submit">Submit</button>
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <table class="table" id="id_table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Category</th>
                                <th>SubCategory</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if records %}
                            {% for record in records %}
                            <tr>
                                <td>{{ record.id }}</td>
                                <td>{{ record.category.categories }}</td>
                                <td>{{ record.subcategory }}</td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            No Data Found..
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        
        <!-- Jquery JS -->
        <script src="{% static 'jquery-3.5.1/jquery.min.js' %}" crossorigin="anonymous"></script>
        <!-- Bootstrap JS -->
        <script src="{% static 'bootstrap-4.0.0/js/bootstrap.min.js' %}" crossorigin="anonymous"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $("#id_category").on("change", function(){
                    var category_id = $('#id_category').val();
                    $('#id_subcategory').empty();
                    $('#id_subcategory').append('<option value="" selected disabled>Select SubCategory</option>');
                    $.ajax({
                        method: 'GET',
                        url: "{% url 'get_subcategory' %}",
                        data: { 'category_id': category_id },
                        datatype: 'json',
                        success: function (data) {
                            if (data.success == true) {
                                $.each(data.records, function (k, v) {
                                    $('#id_subcategory').append('<option value="' + v.subcategory + '">' + v.subcategory + '</option>');
                                });
                            }
                            else {
                                alert(data.message);
                            }
                        },
                        error: function (data) {
                            console.log(data.message);
                        },
                    });
                })

                // On Submit the form
                $("#id_form").submit(function(e){
                    e.preventDefault();
                    var form = $(this);
                    $("#id_table tbody").empty();
                    $.ajax({
                        method: 'POST',
                        url: "{% url 'category_view' %}",
                        data: form.serialize(),
                        datatype: 'json',
                        success: function (data) {
                            console.log(data);
                            if (data.success == true) {
                                $.each(data.records, function (k, v) {
                                    $('#id_table tbody').append('<tr><td>'+v.id+'</td><td>'+v.category_id+'</td><td>'+v.subcategory+'</td></tr>');
                                });
                            }
                            else {
                                alert(data.errors);
                            }
                        },
                        error: function (data) {
                            console.log(data.message);
                        },
                    });
                })
            })
        </script>
    </body>
</html>